name: CI/CD 자동화

on:
  push:
    branches: [ master ]

jobs:
  build-push-deploy:
    runs-on: ubuntu-22.04 
    steps:
    - name: 코드 체크아웃
      uses: actions/checkout@v3

    - name: Docker Buildx 설정
      uses: docker/setup-buildx-action@v2

    - name: GCP JSON Key 파일 생성
      run: |
        mkdir -p apps/server/src/configs
        echo '${{ secrets.GCP_KEY_JSON }}' > apps/server/src/configs/superb-app-428715-m2-70554e73216e.json

    - name: NCR 로그인
      uses: docker/login-action@v2
      with:
        registry: hotsix-blog.kr.ncr.ntruss.com
        username: ${{ secrets.NCP_ACCESS_KEY }}
        password: ${{ secrets.NCP_SECRET_KEY }}

    - name: 도커 이미지 빌드 및 푸시
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: |
          hotsix-blog.kr.ncr.ntruss.com/hotsix-blog:latest

    - name: 서버 배포
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: 22
        script: |
          docker login hotsix-blog.kr.ncr.ntruss.com -u ${{ secrets.NCP_ACCESS_KEY }} -p ${{ secrets.NCP_SECRET_KEY }}
          docker pull hotsix-blog.kr.ncr.ntruss.com/hotsix-blog:latest
          docker stop hotsix-blog-container || true
          docker rm hotsix-blog-container || true
          docker run -d --name hotsix-blog-container -p 3001:3001 hotsix-blog.kr.ncr.ntruss.com/hotsix-blog:latest \
            -e NODE_ENV=production \
            -e DB_HOST=${{ secrets.DB_HOST }} \
            -e DB_PORT=${{ secrets.DB_PORT }} \
            -e DB_USERNAME=${{ secrets.DB_USERNAME }}
            -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
            -e DB_NAME=${{ secrets.DB_NAME }}

    - name: 도커 이미지 다이제스트 출력
      run: echo ${{ steps.docker_build.outputs.digest }}