name: CI/CD 자동화

on:
  push:
    branches: [ nullisdefined ]

jobs:
  build-and-push:
    runs-on: ubuntu-22.04
    steps:
    - name: 코드 체크아웃
      uses: actions/checkout@v2

    - name: Docker 빌드
      run: |
        docker build -t hotsix-blog.kr.ncr.ntruss.com/hotsix-blog:${{ github.sha }} .

    - name: NCR 로그인
      uses: docker/login-action@v1
      with:
        registry: hotsix-blog.kr.ncr.ntruss.com
        username: ${{ secrets.NCP_ACCESS_KEY }}
        password: ${{ secrets.NCP_SECRET_KEY }}

    - name: 이미지 푸시
      run: |
        docker push hotsix-blog.kr.ncr.ntruss.com/hotsix-blog:${{ github.sha }}

    - name: 서버 배포
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          docker login hotsix-blog.kr.ncr.ntruss.com -u ${{ secrets.NCP_ACCESS_KEY }} -p ${{ secrets.NCP_SECRET_KEY }}
          docker pull hotsix-blog.kr.ncr.ntruss.com/hotsix-blog:${{ github.sha }}
          docker stop hotsix-blog-container || true
          docker rm hotsix-blog-container || true
          docker run -d --name hotsix-blog-container -p 3001:3001 hotsix-blog.kr.ncr.ntruss.com/hotsix-blog:${{ github.sha }}